# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Fera.Model.Address do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :company,
    :name,
    :address1,
    :address2,
    :city_name,
    :region_name,
    :country_code,
    :zip_code,
    :phone
  ]

  @type t :: %__MODULE__{
    :company => String.t | nil,
    :name => String.t | nil,
    :address1 => String.t | nil,
    :address2 => String.t | nil,
    :city_name => String.t | nil,
    :region_name => String.t | nil,
    :country_code => String.t | nil,
    :zip_code => String.t | nil,
    :phone => String.t | nil
  }

  def decode(value) do
    value
  end
end

