# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Fera.Model.CreateWebhook422Response do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :message,
    :errors
  ]

  @type t :: %__MODULE__{
    :message => String.t | nil,
    :errors => map() | nil
  }

  def decode(value) do
    value
  end
end

