# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Fera.Model.CreateWebhookRequestData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :event_name,
    :url
  ]

  @type t :: %__MODULE__{
    :event_name => String.t,
    :url => String.t
  }

  def decode(value) do
    value
  end
end

