# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Fera.Model.CreateReviewRequestDataProduct do
  @moduledoc """
  Product attributes to find or create with.  If the product does not exist by external_id provided, then it will be created.
  """

  @derive Jason.Encoder
  defstruct [
    :external_id,
    :name,
    :url,
    :price,
    :thumbnail_url
  ]

  @type t :: %__MODULE__{
    :external_id => String.t | nil,
    :name => String.t | nil,
    :url => String.t | nil,
    :price => float() | nil,
    :thumbnail_url => String.t | nil
  }

  def decode(value) do
    value
  end
end

