# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Fera.Model.CreateReviewRequestDataCustomer do
  @moduledoc """
  Customer attributes to find or create with.  If the customer does not exist by `external_id` or `email` provided, then Fera will create a new customer record and link it to the current review.
  """

  @derive Jason.Encoder
  defstruct [
    :external_id,
    :name,
    :email
  ]

  @type t :: %__MODULE__{
    :external_id => String.t | nil,
    :name => String.t | nil,
    :email => String.t | nil
  }

  def decode(value) do
    value
  end
end

