# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Fera.Model.CreateMediaRequestData do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :review_id,
    :caption,
    :state,
    :file,
    :review_channel_code,
    :is_verified,
    :external_customer_id,
    :customer_id,
    :external_product_id,
    :product_id,
    :customer,
    :product,
    :external_order_id,
    :order_id
  ]

  @type t :: %__MODULE__{
    :review_id => String.t | nil,
    :caption => String.t | nil,
    :state => String.t | nil,
    :file => String.t,
    :review_channel_code => String.t | nil,
    :is_verified => boolean() | nil,
    :external_customer_id => String.t | nil,
    :customer_id => String.t | nil,
    :external_product_id => String.t | nil,
    :product_id => String.t | nil,
    :customer => Fera.Model.CreateReviewRequestDataCustomer.t | nil,
    :product => Fera.Model.CreateReviewRequestDataProduct.t | nil,
    :external_order_id => String.t | nil,
    :order_id => String.t | nil
  }

  alias Fera.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:customer, :struct, Fera.Model.CreateReviewRequestDataCustomer)
     |> Deserializer.deserialize(:product, :struct, Fera.Model.CreateReviewRequestDataProduct)
  end
end

