# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Fera.Model.CustomerWithoutNesting do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :display_name,
    :is_anonymous,
    :display_location,
    :avatar_url,
    :default_avatar_url,
    :rating,
    :external_id,
    :email,
    :name,
    :generated_display_name,
    :is_name_visible,
    :generated_display_location,
    :is_location_visible,
    :country_code,
    :region_name,
    :city,
    :zip,
    :is_test,
    :submission_url,
    :counts,
    :notes,
    :tags,
    :external_created_at,
    :created_at,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :display_name => String.t | nil,
    :is_anonymous => boolean() | nil,
    :display_location => String.t | nil,
    :avatar_url => String.t | nil,
    :default_avatar_url => String.t | nil,
    :rating => Fera.Model.CustomerRating.t | nil,
    :external_id => String.t | nil,
    :email => String.t | nil,
    :name => String.t | nil,
    :generated_display_name => String.t | nil,
    :is_name_visible => boolean() | nil,
    :generated_display_location => String.t | nil,
    :is_location_visible => boolean() | nil,
    :country_code => String.t | nil,
    :region_name => String.t | nil,
    :city => String.t | nil,
    :zip => String.t | nil,
    :is_test => boolean() | nil,
    :submission_url => String.t | nil,
    :counts => Fera.Model.CustomerCounts.t | nil,
    :notes => String.t | nil,
    :tags => [String.t] | nil,
    :external_created_at => DateTime.t | nil,
    :created_at => DateTime.t | nil,
    :updated_at => DateTime.t | nil
  }

  alias Fera.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:rating, :struct, Fera.Model.CustomerRating)
     |> Deserializer.deserialize(:counts, :struct, Fera.Model.CustomerCounts)
     |> Deserializer.deserialize(:external_created_at, :datetime, nil)
     |> Deserializer.deserialize(:created_at, :datetime, nil)
     |> Deserializer.deserialize(:updated_at, :datetime, nil)
  end
end

