# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Fera.Model.DeclineReviewRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :reasons
  ]

  @type t :: %__MODULE__{
    :reasons => [String.t]
  }

  def decode(value) do
    value
  end
end

