# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Fera.Model.DeliverOrderRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :delivered_at
  ]

  @type t :: %__MODULE__{
    :delivered_at => DateTime.t | nil
  }

  alias Fera.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:delivered_at, :datetime, nil)
  end
end

