# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Fera.Model.LineItem do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :product_id,
    :variant_id,
    :quantity,
    :name,
    :total,
    :total_usd
  ]

  @type t :: %__MODULE__{
    :product_id => String.t | nil,
    :variant_id => String.t | nil,
    :quantity => integer() | nil,
    :name => String.t | nil,
    :total => float() | nil,
    :total_usd => float() | nil
  }

  def decode(value) do
    value
  end
end

