# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Fera.Model.ListMetaParam do
  @moduledoc """
  Pagination and count information about the list of objects retrieved.
  """

  @derive Jason.Encoder
  defstruct [
    :page,
    :page_size,
    :page_count,
    :limit,
    :offset,
    :total_count
  ]

  @type t :: %__MODULE__{
    :page => integer() | nil,
    :page_size => integer() | nil,
    :page_count => integer() | nil,
    :limit => integer() | nil,
    :offset => integer() | nil,
    :total_count => integer() | nil
  }

  def decode(value) do
    value
  end
end

