# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Fera.Model.Media do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :subject,
    :is_verified,
    :is_test,
    :external_product_id,
    :product_id,
    :external_customer_id,
    :customer_id,
    :created_at,
    :updated_at,
    :type,
    :review_id,
    :review_channel_code,
    :url,
    :thumbnail_url,
    :processing_state,
    :channel_code,
    :caption,
    :state,
    :external_order_id,
    :order_id,
    :product,
    :customer
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :subject => String.t | nil,
    :is_verified => boolean() | nil,
    :is_test => boolean() | nil,
    :external_product_id => String.t | nil,
    :product_id => String.t | nil,
    :external_customer_id => String.t | nil,
    :customer_id => String.t | nil,
    :created_at => DateTime.t | nil,
    :updated_at => DateTime.t | nil,
    :type => String.t | nil,
    :review_id => String.t | nil,
    :review_channel_code => String.t | nil,
    :url => String.t | nil,
    :thumbnail_url => String.t | nil,
    :processing_state => String.t | nil,
    :channel_code => String.t | nil,
    :caption => String.t | nil,
    :state => String.t | nil,
    :external_order_id => String.t | nil,
    :order_id => String.t | nil,
    :product => Fera.Model.ProductWithoutNesting.t | nil,
    :customer => Fera.Model.CustomerWithoutNesting.t | nil
  }

  alias Fera.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_at, :datetime, nil)
     |> Deserializer.deserialize(:updated_at, :datetime, nil)
     |> Deserializer.deserialize(:product, :struct, Fera.Model.ProductWithoutNesting)
     |> Deserializer.deserialize(:customer, :struct, Fera.Model.CustomerWithoutNesting)
  end
end

