# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Fera.Model.Message do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :external_customer_id,
    :customer_id,
    :external_order_id,
    :order_id,
    :created_at,
    :updated_at,
    :customer,
    :content_campaign,
    :products,
    :submissions,
    :active_submission,
    :reviews
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :external_customer_id => String.t | nil,
    :customer_id => String.t | nil,
    :external_order_id => String.t | nil,
    :order_id => String.t | nil,
    :created_at => DateTime.t | nil,
    :updated_at => DateTime.t | nil,
    :customer => Fera.Model.CustomerWithoutNesting.t | nil,
    :content_campaign => Fera.Model.ContentCampaignWithoutNesting.t | nil,
    :products => [Fera.Model.ProductWithoutNesting.t] | nil,
    :submissions => [Fera.Model.SubmissionWithoutNesting.t] | nil,
    :active_submission => Fera.Model.SubmissionWithoutNesting.t | nil,
    :reviews => [Fera.Model.ReviewWithoutNesting.t] | nil
  }

  alias Fera.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_at, :datetime, nil)
     |> Deserializer.deserialize(:updated_at, :datetime, nil)
     |> Deserializer.deserialize(:customer, :struct, Fera.Model.CustomerWithoutNesting)
     |> Deserializer.deserialize(:content_campaign, :struct, Fera.Model.ContentCampaignWithoutNesting)
     |> Deserializer.deserialize(:products, :list, Fera.Model.ProductWithoutNesting)
     |> Deserializer.deserialize(:submissions, :list, Fera.Model.SubmissionWithoutNesting)
     |> Deserializer.deserialize(:active_submission, :struct, Fera.Model.SubmissionWithoutNesting)
     |> Deserializer.deserialize(:reviews, :list, Fera.Model.ReviewWithoutNesting)
  end
end

