# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Fera.Model.Order do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :external_id,
    :external_customer_id,
    :customer_id,
    :line_items,
    :number,
    :total,
    :currency,
    :total_usd,
    :customer_name,
    :customer_email,
    :billing_address,
    :shipping_address,
    :is_test,
    :is_cancelled,
    :external_created_at,
    :external_updated_at,
    :paid_at,
    :fulfilled_at,
    :delivered_at,
    :status,
    :submission_url,
    :counts,
    :rating,
    :notes,
    :tags,
    :created_at,
    :updated_at,
    :customer,
    :media
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :external_id => String.t | nil,
    :external_customer_id => String.t | nil,
    :customer_id => String.t | nil,
    :line_items => [Fera.Model.LineItem.t] | nil,
    :number => integer() | nil,
    :total => float() | nil,
    :currency => String.t | nil,
    :total_usd => float() | nil,
    :customer_name => String.t | nil,
    :customer_email => String.t | nil,
    :billing_address => Fera.Model.Address.t | nil,
    :shipping_address => Fera.Model.Address.t | nil,
    :is_test => boolean() | nil,
    :is_cancelled => boolean() | nil,
    :external_created_at => DateTime.t | nil,
    :external_updated_at => DateTime.t | nil,
    :paid_at => DateTime.t | nil,
    :fulfilled_at => DateTime.t | nil,
    :delivered_at => DateTime.t | nil,
    :status => String.t | nil,
    :submission_url => String.t | nil,
    :counts => Fera.Model.OrderCounts.t | nil,
    :rating => Fera.Model.OrderRating.t | nil,
    :notes => String.t | nil,
    :tags => [String.t] | nil,
    :created_at => DateTime.t | nil,
    :updated_at => DateTime.t | nil,
    :customer => Fera.Model.CustomerWithoutNesting.t | nil,
    :media => [Fera.Model.MediaWithoutNesting.t] | nil
  }

  alias Fera.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:line_items, :list, Fera.Model.LineItem)
     |> Deserializer.deserialize(:billing_address, :struct, Fera.Model.Address)
     |> Deserializer.deserialize(:shipping_address, :struct, Fera.Model.Address)
     |> Deserializer.deserialize(:external_created_at, :datetime, nil)
     |> Deserializer.deserialize(:external_updated_at, :datetime, nil)
     |> Deserializer.deserialize(:paid_at, :datetime, nil)
     |> Deserializer.deserialize(:fulfilled_at, :datetime, nil)
     |> Deserializer.deserialize(:delivered_at, :datetime, nil)
     |> Deserializer.deserialize(:counts, :struct, Fera.Model.OrderCounts)
     |> Deserializer.deserialize(:rating, :struct, Fera.Model.OrderRating)
     |> Deserializer.deserialize(:created_at, :datetime, nil)
     |> Deserializer.deserialize(:updated_at, :datetime, nil)
     |> Deserializer.deserialize(:customer, :struct, Fera.Model.CustomerWithoutNesting)
     |> Deserializer.deserialize(:media, :list, Fera.Model.MediaWithoutNesting)
  end
end

