# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Fera.Model.ProductCounts do
  @moduledoc """
  Cached counts related to the product.
  """

  @derive Jason.Encoder
  defstruct [
    :reviews,
    :media,
    :photos,
    :videos
  ]

  @type t :: %__MODULE__{
    :reviews => float() | nil,
    :media => float() | nil,
    :photos => float() | nil,
    :videos => float() | nil
  }

  def decode(value) do
    value
  end
end

