# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Fera.Model.ReviewWithoutNesting do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :subject,
    :is_verified,
    :is_test,
    :external_product_id,
    :product_id,
    :external_customer_id,
    :customer_id,
    :created_at,
    :updated_at,
    :rating,
    :heading,
    :body,
    :is_from_supplier,
    :store_reply,
    :counts,
    :state,
    :external_order_id,
    :order_id
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :subject => String.t | nil,
    :is_verified => boolean() | nil,
    :is_test => boolean() | nil,
    :external_product_id => String.t | nil,
    :product_id => String.t | nil,
    :external_customer_id => String.t | nil,
    :customer_id => String.t | nil,
    :created_at => DateTime.t | nil,
    :updated_at => DateTime.t | nil,
    :rating => integer() | nil,
    :heading => String.t | nil,
    :body => String.t | nil,
    :is_from_supplier => boolean() | nil,
    :store_reply => Fera.Model.UpdateReviewRequestStoreReply.t | nil,
    :counts => Fera.Model.ReviewCounts.t | nil,
    :state => String.t | nil,
    :external_order_id => String.t | nil,
    :order_id => String.t | nil
  }

  alias Fera.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_at, :datetime, nil)
     |> Deserializer.deserialize(:updated_at, :datetime, nil)
     |> Deserializer.deserialize(:store_reply, :struct, Fera.Model.UpdateReviewRequestStoreReply)
     |> Deserializer.deserialize(:counts, :struct, Fera.Model.ReviewCounts)
  end
end

