# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Fera.Model.ReviewCounts do
  @moduledoc """
  Cached counts of child objects.
  """

  @derive Jason.Encoder
  defstruct [
    :media,
    :photos,
    :videos
  ]

  @type t :: %__MODULE__{
    :media => integer() | nil,
    :photos => integer() | nil,
    :videos => integer() | nil
  }

  def decode(value) do
    value
  end
end

