# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Fera.Model.StoreCounts do
  @moduledoc """
  Cached counts related to the store.
  """

  @derive Jason.Encoder
  defstruct [
    :reviews,
    :media
  ]

  @type t :: %__MODULE__{
    :reviews => float() | nil,
    :media => float() | nil
  }

  def decode(value) do
    value
  end
end

