# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Fera.Model.Submission do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :external_customer_id,
    :customer_id,
    :created_at,
    :updated_at,
    :customer,
    :customer_message,
    :content_campaign
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :external_customer_id => String.t | nil,
    :customer_id => String.t | nil,
    :created_at => DateTime.t | nil,
    :updated_at => DateTime.t | nil,
    :customer => Fera.Model.CustomerWithoutNesting.t | nil,
    :customer_message => Fera.Model.MessageWithoutNesting.t | nil,
    :content_campaign => Fera.Model.ContentCampaignWithoutNesting.t | nil
  }

  alias Fera.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_at, :datetime, nil)
     |> Deserializer.deserialize(:updated_at, :datetime, nil)
     |> Deserializer.deserialize(:customer, :struct, Fera.Model.CustomerWithoutNesting)
     |> Deserializer.deserialize(:customer_message, :struct, Fera.Model.MessageWithoutNesting)
     |> Deserializer.deserialize(:content_campaign, :struct, Fera.Model.ContentCampaignWithoutNesting)
  end
end

