# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Fera.Model.UpdateReviewRequestStoreReply do
  @moduledoc """
  Store admin reply to the customer's review, if any.
  """

  @derive Jason.Encoder
  defstruct [
    :body,
    :created_at
  ]

  @type t :: %__MODULE__{
    :body => String.t | nil,
    :created_at => DateTime.t | nil
  }

  alias Fera.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:created_at, :datetime, nil)
  end
end

