# NOTE: This file is auto generated by OpenAPI Generator 7.5.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Fera.Api.Customers do
  @moduledoc """
  API calls for all endpoints tagged `Customers`.
  """

  alias Fera.Connection
  import Fera.RequestBuilder

  @doc """
  Create Customer
  Create new customer.

  ### Parameters

  - `connection` (Fera.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:body` (CreateCustomerRequest): Object creation attributes.

  ### Returns

  - `{:ok, Fera.Model.Customer.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_customer(Tesla.Env.client, keyword()) :: {:ok, Fera.Model.Customer.t} | {:ok, Map.t} | {:error, Tesla.Env.t}
  def create_customer(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/customers")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, Fera.Model.Customer},
      {422, false}
    ])
  end

  @doc """
  Delete Customer
  Delete specific customer.

  ### Parameters

  - `connection` (Fera.Connection): Connection to server
  - `id` (String.t): ID of the customer you want to delete. External ID is also accepted here
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_customer(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, Map.t} | {:error, Tesla.Env.t}
  def delete_customer(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/customers/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {404, false},
      {405, false}
    ])
  end

  @doc """
  List Customer Photos & Videos
  Retrieve a list of media that belong to a customer, if any.

  ### Parameters

  - `connection` (Fera.Connection): Connection to server
  - `id` (String.t): Fera  or external ID of the customer
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): Current page number, if pagination used.
    - `:page_size` (integer()): Number of items per page.
    - `:limit` (integer()): Maximum number of items retrieved.
    - `:offset` (integer()): Starting position of items request query.
    - `:"product.id"` (String.t): Filter by Fera product ID or external product ID.
    - `:"product.ids"` (String.t): Filter by multiple Fera product IDs or external product IDs. Comma-separated list or array of fields accepted.
    - `:"customer.external_id"` (String.t): External customer ID (usually the Wix, Shopify or other eCommerce platform customer ID).
    - `:customer_id` (String.t): Filter by Fera customer ID or external customer ID.
    - `:"order.id"` (String.t): Filter by Fera order ID or external order ID.
    - `:subject` (String.t): Filter by what the resource is describing; A specific product, the entire store (ie overall experience) or both (all). Default: both.
    - `:verified` (boolean()): Only show content submitted by verified sources (or unverified sources).
    - `:state` (String.t): State of the resource. Resources are initially in the `pending_approval` state when submitted by customers from the storefront.
    - `:type` (String.t): Type of media: `photo` or `video`.    Can also be used to filter the subject at the same time. For example: `product_photo`.
    - `:"review.id"` (String.t): Review that the media is a part of (submitted along with).
    - `:sort_by` (String.t): Sort (order) the response results by the given attribute.  Add `:desc` to sort in descending order, or `:asc` to sort in ascending order.  For example: created_at:desc would get you created_at in descending order.

  ### Returns

  - `{:ok, Fera.Model.ListCustomerMedia200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_customer_media(Tesla.Env.client, String.t, keyword()) :: {:ok, Fera.Model.ListCustomerMedia200Response.t} | {:ok, Map.t} | {:error, Tesla.Env.t}
  def list_customer_media(connection, id, opts \\ []) do
    optional_params = %{
      :page => :query,
      :page_size => :query,
      :limit => :query,
      :offset => :query,
      :"product.id" => :query,
      :"product.ids" => :query,
      :"customer.external_id" => :query,
      :customer_id => :query,
      :"order.id" => :query,
      :subject => :query,
      :verified => :query,
      :state => :query,
      :type => :query,
      :"review.id" => :query,
      :sort_by => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/customers/#{id}/media")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Fera.Model.ListCustomerMedia200Response},
      {404, false}
    ])
  end

  @doc """
  List Customer Reviews
  Retrieve a list of reviews that belong to a customer, if any.

  ### Parameters

  - `connection` (Fera.Connection): Connection to server
  - `id` (String.t): Fera  or external ID of the customer
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): Current page number, if pagination used.
    - `:page_size` (integer()): Number of items per page.
    - `:limit` (integer()): Maximum number of items retrieved.
    - `:offset` (integer()): Starting position of items request query.
    - `:"product.id"` (String.t): Filter by Fera product ID or external product ID.
    - `:"product.ids"` (String.t): Filter by multiple Fera product IDs or external product IDs. Comma-separated list or array of fields accepted.
    - `:"customer.external_id"` (String.t): External customer ID (usually the Wix, Shopify or other eCommerce platform customer ID).
    - `:customer_id` (String.t): Filter by Fera customer ID or external customer ID.
    - `:"order.id"` (String.t): Filter by Fera order ID or external order ID.
    - `:subject` (String.t): Filter by what the resource is describing; A specific product, the entire store (ie overall experience) or both (all). Default: both.
    - `:verified` (boolean()): Only show content submitted by verified sources (or unverified sources).
    - `:state` (String.t): State of the resource. Resources are initially in the `pending_approval` state when submitted by customers from the storefront.
    - `:source` (String.t): Source from where reviews can be added. Resources are when submitted by customers from the storefront, imported from external review app or using csv import, manual import.
    - `:channel_code` (String.t): Review Channel from where reviews are synced. e.g. amazon, facebook, trustpilot, etc.
    - `:rating` (String.t): Search for customer reviews by rating.
    - `:only_with_content` (String.t): Only show reviews with any textual content (summary or body).
    - `:"customer.email"` (String.t): Filter by customer email
    - `:search` (String.t): Search by any of the following columns: `id`, `product.id`, `product.external_id`, `product.sku`, `customer.id`, `customer.external_id`, `customer.email`, `customer.name`, `media[*].id`, etc
    - `:"counts.media"` (String.t): Search for a customer by the number of media(photos or videos) they have submitted.
    - `:date_created` (String.t): Search for customer reviews within a date range using the created_at date.
    - `:sort_by` (String.t): Sort (order) the response results by the given attribute.  Add `:desc` to sort in descending order, or `:asc` to sort in ascending order.  For example: created_at:desc would get you created_at in descending order.

  ### Returns

  - `{:ok, Fera.Model.ListCustomerReviews200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_customer_reviews(Tesla.Env.client, String.t, keyword()) :: {:ok, Fera.Model.ListCustomerReviews200Response.t} | {:ok, Map.t} | {:error, Tesla.Env.t}
  def list_customer_reviews(connection, id, opts \\ []) do
    optional_params = %{
      :page => :query,
      :page_size => :query,
      :limit => :query,
      :offset => :query,
      :"product.id" => :query,
      :"product.ids" => :query,
      :"customer.external_id" => :query,
      :customer_id => :query,
      :"order.id" => :query,
      :subject => :query,
      :verified => :query,
      :state => :query,
      :source => :query,
      :channel_code => :query,
      :rating => :query,
      :only_with_content => :query,
      :"customer.email" => :query,
      :search => :query,
      :"counts.media" => :query,
      :date_created => :query,
      :sort_by => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/customers/#{id}/reviews")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Fera.Model.ListCustomerReviews200Response},
      {404, false}
    ])
  end

  @doc """
  List Customers
  Retrieve a list of customers.

  ### Parameters

  - `connection` (Fera.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:page` (integer()): Current page number, if pagination used.
    - `:page_size` (integer()): Number of items per page.
    - `:limit` (integer()): Maximum number of items retrieved.
    - `:offset` (integer()): Starting position of items request query.
    - `:"customer.external_id"` (String.t): External customer ID (usually the Wix, Shopify or other eCommerce platform customer ID).
    - `:email` (String.t): Email address of the customer.
    - `:search` (String.t): Search for a customer by email, external ID or Fera ID.
    - `:"counts.reviews"` (String.t): Search for a customer by the number of reviews they have submitted.
    - `:rating` (String.t): Search for customers by rating.
    - `:"counts.orders"` (String.t): Search for a customer by the number of orders they have placed.
    - `:"counts.media"` (String.t): Search for a customer by the number of media(photos or videos) they have submitted.
    - `:external_created_at` (String.t): Search for customers within a date range using the external_created_at date, with fallback to the internal created_at date.
    - `:sort_by` (String.t): Sort (order) the response results by the given attribute.  Add `:desc` to sort in descending order, or `:asc` to sort in ascending order.  For example: created_at:desc would get you created_at in descending order.

  ### Returns

  - `{:ok, Fera.Model.ListCustomers200Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_customers(Tesla.Env.client, keyword()) :: {:ok, Fera.Model.ListCustomers200Response.t} | {:ok, Map.t} | {:error, Tesla.Env.t}
  def list_customers(connection, opts \\ []) do
    optional_params = %{
      :page => :query,
      :page_size => :query,
      :limit => :query,
      :offset => :query,
      :"customer.external_id" => :query,
      :email => :query,
      :search => :query,
      :"counts.reviews" => :query,
      :rating => :query,
      :"counts.orders" => :query,
      :"counts.media" => :query,
      :external_created_at => :query,
      :sort_by => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/customers")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Fera.Model.ListCustomers200Response},
      {400, false}
    ])
  end

  @doc """
  Retrieve Customer
  Retrieve data for a specific customer.

  ### Parameters

  - `connection` (Fera.Connection): Connection to server
  - `id` (String.t): Fera  or external ID of the customer
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Fera.Model.Customer.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec retrieve_customer(Tesla.Env.client, String.t, keyword()) :: {:ok, Fera.Model.Customer.t} | {:ok, Map.t} | {:error, Tesla.Env.t}
  def retrieve_customer(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/customers/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Fera.Model.Customer},
      {404, false}
    ])
  end

  @doc """
  Update Customer
  Update data for a specific customer.

  ### Parameters

  - `connection` (Fera.Connection): Connection to server
  - `id` (String.t): ID of the customer you want to update. External ID is also accepted here
  - `opts` (keyword): Optional parameters
    - `:body` (CreateCustomerRequestData): Object creation attributes.

  ### Returns

  - `{:ok, Fera.Model.Customer.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_customer(Tesla.Env.client, String.t, keyword()) :: {:ok, Fera.Model.Customer.t} | {:ok, Map.t} | {:error, Tesla.Env.t}
  def update_customer(connection, id, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:put)
      |> url("/customers/#{id}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {202, Fera.Model.Customer},
      {404, false},
      {422, false}
    ])
  end
end
